name: Build images
'on':
  push:
    branches:
    - main
    paths-ignore:
    - "README.md"
    - "docs/**"
concurrency:
  group: images-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  api:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: fredrir/infra/.github/workflows/build-image.yml@b4cb44834b5d1dbccbbf34e5f022bef4ec448dc9
    with:
      image: ghcr.io/fredrir/y-api
      context: .
      dockerfile: Dockerfile
      recipe: y-api
  web:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: fredrir/infra/.github/workflows/build-image.yml@b4cb44834b5d1dbccbbf34e5f022bef4ec448dc9
    with:
      image: ghcr.io/fredrir/y-web
      context: .
      dockerfile: Dockerfile
      recipe: y-web
      check-target: check-reports
